import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the OpenNext adapter: a copy of the server bundle plus every dependency
    // it inlines. Linting it reported 1,888 warnings in code nobody wrote, which is how a
    // lint step becomes a thing people stop reading.
    ".open-next/**",
    "node_modules/**",
  ]),
]);

export default eslintConfig;
